In [44]:
import pandas as pd
import numpy as np


sousAlimentationCsv = pd.read_csv("/Users/yassine/Desktop/data-python/fr_sousalimentation.csv");
sousAlimentationCsv=sousAlimentationCsv[['Code année','Année','Zone','Code zone','Valeur']];
sousAlimentationCsv.loc[sousAlimentationCsv['Année'] == "2012-2014"];
sousAlimentationCsv['Année'] = '2013';
sousAlimentationCsv["Valeur"] = pd.to_numeric(sousAlimentationCsv["Valeur"],errors='coerce')
sousAlimentationCsv['underfeed'] = sousAlimentationCsv['Valeur'] * 100000
sousAlimentationCsv.rename(columns={"Valeur":"SsAliment"})


sousAlimentationCsv

      Code année Année         Zone  Code zone  Valeur  underfeed
0       20122014  2013  Afghanistan          2     7.9   790000.0
1       20132015  2013  Afghanistan          2     8.8   880000.0
2       20142016  2013  Afghanistan          2     9.6   960000.0
3       20152017  2013  Afghanistan          2    10.2  1020000.0
4       20162018  2013  Afghanistan          2    10.6  1060000.0
...          ...   ...          ...        ...     ...        ...
1015    20122014  2013     Zimbabwe        181     6.6   660000.0
1016    20132015  2013     Zimbabwe        181     7.2   720000.0
1017    20142016  2013     Zimbabwe        181     7.8   780000.0
1018    20152017  2013     Zimbabwe        181     8.2   820000.0
1019    20162018  2013     Zimbabwe        181     8.5   850000.0

[1020 rows x 6 columns]

In [45]:
pop=pd.read_csv("/Users/yassine/Desktop/data-python/fr_population.csv")
pop=pop[['Zone','Valeur','Code zone']]
pop['Valeur']=pop['Valeur']*1000
pop=pop.rename(columns={"Valeur":"population", "Zone":"pays"})
pop.loc[pop['pays']!= 'Chine',:]



sousAlimentationPopulation = pd.merge(left=sousAlimentationCsv, right=pop, left_on='Code zone', right_on='Code zone')
sousAlimentationPopulation['ProportionSsAlimentPopulation'] = (sousAlimentationPopulation['underfeed'] * 100) / sousAlimentationPopulation['population']



sousAlimentationPopulation

,Code année,Année,Zone,Code zone,Valeur,underfeed,pays,population,ProportionSsAlimentPopulation
0,20122014,2013,Afghanistan,2,7.9,790000.0,Afghanistan,30552000,2.585755
1,20132015,2013,Afghanistan,2,8.8,880000.0,Afghanistan,30552000,2.880335
2,20142016,2013,Afghanistan,2,9.6,960000.0,Afghanistan,30552000,3.142184
3,20152017,2013,Afghanistan,2,10.2,1020000.0,Afghanistan,30552000,3.338570
4,20162018,2013,Afghanistan,2,10.6,1060000.0,Afghanistan,30552000,3.469495
...,...,...,...,...,...,...,...,...,...
870,20122014,2013,Zimbabwe,181,6.6,660000.0,Zimbabwe,14150000,4.664311
871,20132015,2013,Zimbabwe,181,7.2,720000.0,Zimbabwe,14150000,5.088339
872,20142016,2013,Zimbabwe,181,7.8,780000.0,Zimbabwe,14150000,5.512367
873,20152017,2013,Zimbabwe,181,8.2,820000.0,Zimbabwe,14150000,5.795053
874,20162018,2013,Zimbabwe,181,8.5,850000.0,Zimbabwe,14150000,6.007067

In [42]:
# Import des données des bilans alimentaires 
veg = pd.read_csv("/Users/yassine/Desktop/data-python/fr_vegetaux.csv")
ani = pd.read_csv("/Users/yassine/Desktop/data-python/fr_animaux.csv")


# Ajout de la variable origin
ani["Origine"] = "animale"
veg["Origine"] = "vegetale"


# On regroupe veg et ani en un unique dataframe, via une union
temp = ani.append(veg)


# Suppression de ani et veg
del ani, veg


# Transformation de temp en table pivot
data = temp.pivot_table(index=["Zone","Produit","Code Produit","Origine"],
                        columns = ["Élément"], values=["Valeur"], aggfunc=sum)

data.columns = ['Aliments pour animaux', 'Autres Utilisations', 'Disponibilité alimentaire (Kcal/personne/jour)', 
                'Disponibilité alimentaire en quantité (kg/personne/an)', 
                'Disponibilité de matière grasse en quantité (g/personne/jour)', 
                'Disponibilité de protéines en quantité (g/personne/jour)', 'Disponibilité intérieure', 
                'Exportations - Quantité', 'Importations - Quantité', 'Nourriture', 'Pertes', 'Production', 
                'Semences', 'Traitement', 'Variation de stock']


dispo_alimentaire = data.reset_index()

#Nourriture = nouriture pour humain

dispo_alimentaire

,Zone,Produit,Code Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,2736,animale,NaN,NaN,5.0,1.72,0.20,0.77,53.0,NaN,NaN,53.0,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",2614,vegetale,NaN,NaN,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,2680,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,2.0,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,2618,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,2615,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,82.0,NaN,82.0,82.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15697,Îles Salomon,Viande de Suides,2733,animale,NaN,NaN,45.0,4.70,4.28,1.41,3.0,NaN,0.0,3.0,NaN,2.0,NaN,NaN,NaN
15698,Îles Salomon,Viande de Volailles,2734,animale,NaN,NaN,11.0,3.34,0.69,1.14,2.0,NaN,2.0,2.0,NaN,0.0,NaN,NaN,NaN
15699,Îles Salomon,"Viande, Autre",2735,animale,NaN,NaN,0.0,0.06,NaN,0.04,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
15700,Îles Salomon,Vin,2655,vegetale,NaN,NaN,0.0,0.07,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
15701,Îles Salomon,"Épices, Autres",2645,vegetale,NaN,NaN,4.0,0.48,0.21,0.15,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN

In [69]:
sousAlimentationDispoAlim = pd.merge(left=dispo_alimentaire, right=sousAlimentationPopulation, left_on='Zone', right_on='Zone')


unsetImportationNoneValues = sousAlimentationDispoAlim.loc[sousAlimentationDispoAlim['Importations - Quantité'] > 0,:]

unsetImportationNoneValues.sort_values('Importations - Quantité')

importations = unsetImportationNoneValues[['Code zone','Zone','Produit','Importations - Quantité','Exportations - Quantité','Autres Utilisations','Disponibilité intérieure']]

rankImportations = importations.sort_values(by=['Importations - Quantité'], ascending=False)[:200]

rankImportations.drop_duplicates()


##le ratio entre la quantité destinés aux "Autres utilisations" (Other uses) et la disponibilité intérieure.

sortExport = rankImportations.sort_values("Exportations - Quantité", ascending=False)[:-15]

sortExport = sortExport.drop_duplicates(subset=['Produit'])

sortExport['ratio/dispoInt/autreUtil'] = sortExport['Autres Utilisations'] / sortExport['Disponibilité intérieure']



sortExport

,Code zone,Zone,Produit,Importations - Quantité,Exportations - Quantité,Autres Utilisations,Disponibilité intérieure,ratio/dispoInt/autreUtil
77247,231,États-Unis d'Amérique,Blé,5491.0,34691.0,16.0,34051.0,0.000470
1937,79,Allemagne,Lait - Excl Beurre,8332.0,15677.0,504.0,23999.0,0.021001
54765,150,Pays-Bas,"Oranges, Mandarines",5316.0,3695.0,NaN,1471.0,NaN
77425,231,États-Unis d'Amérique,"Légumes, Autres",6944.0,3276.0,NaN,22911.0,NaN
77313,231,États-Unis d'Amérique,"Fruits, Autres",4683.0,2336.0,NaN,7688.0,NaN
15327,351,Chine,Poissons Pelagiques,7557.0,1350.0,40.0,10161.0,0.003937
46030,138,Mexique,Maïs,7261.0,719.0,30.0,31707.0,0.000946
15377,351,Chine,Sucre Eq Brut,5509.0,487.0,13.0,19815.0,0.000656
15366,351,Chine,Soja,65564.0,277.0,1.0,77564.0,0.000013
15218,351,Chine,Manioc,30466.0,203.0,9257.0,34925.0,0.265054
31616,100,Inde,Huile de Palme,8568.0,143.0,6782.0,8413.0,0.806133

In [82]:
sousAlimentationDispoAlim = pd.merge(left=dispo_alimentaire, right=sousAlimentationPopulation, left_on='Zone', right_on='Zone')


unsetImportationNoneValues = sousAlimentationDispoAlim.loc[sousAlimentationDispoAlim['Importations - Quantité'] > 0,:]

unsetImportationNoneValues.sort_values('Importations - Quantité')

importationsForAnlimals = unsetImportationNoneValues[['Origine','Aliments pour animaux','Nourriture','Code zone','Zone','Produit','Importations - Quantité','Exportations - Quantité','Autres Utilisations','Disponibilité intérieure']]

importationsForAnlimals = importationsForAnlimals.sort_values(by=['Importations - Quantité'], ascending=False)[:-15]

importationsForAnlimals.drop_duplicates()




imp = importationsForAnlimals.groupby(['Produit']).sum()

imp = imp.loc[imp['Nourriture'] > 0,:]

imp = imp.loc[imp['Aliments pour animaux'] > 0,:]


##e ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)

imp['ratio/alim+animaux'] = imp['Aliments pour animaux'] / imp['Aliments pour animaux'] + imp['Nourriture']


imp[:-15]

,Aliments pour animaux,Nourriture,Code zone,Importations - Quantité,Exportations - Quantité,Autres Utilisations,Disponibilité intérieure,ratio/alim+animaux
Produit,,,,,,,,
Abats Comestible,5295.0,87685.0,69115,27160.0,25050.0,3480.0,96695.0,87686.0
Arachides Decortiquees,5.0,81105.0,73995,12470.0,12425.0,1695.0,176900.0,81106.0
Avoine,81520.0,19300.0,67825,20305.0,17565.0,100.0,115755.0,19301.0
Bananes,2360.0,239710.0,67690,100125.0,85485.0,195.0,285490.0,239711.0
Bananes plantains,1840.0,20605.0,31215,5620.0,2875.0,0.0,24485.0,20606.0
"Beurre, Ghee",30.0,48290.0,70190,8695.0,8105.0,175.0,48805.0,48291.0
Blé,781810.0,2736050.0,110880,964745.0,995465.0,126860.0,4032270.0,2736051.0
Cephalopodes,180.0,23235.0,46015,11610.0,12760.0,15.0,23430.0,23236.0
Coco (Incl Coprah),230.0,57260.0,59945,12530.0,9080.0,50210.0,209365.0,57261.0
Crustacés,1235.0,89450.0,59740,29690.0,30040.0,220.0,91455.0,89451.0
"Céréales, Autres",98215.0,25360.0,79785,14890.0,12995.0,5720.0,138150.0,25361.0
Dattes,715.0,24945.0,44975,4155.0,2885.0,75.0,27195.0,24946.0
Edulcorants Autres,160.0,105085.0,103175,64300.0,60410.0,27520.0,136620.0,105086.0
Feve de Cacao,10.0,24475.0,90590,43450.0,39775.0,1415.0,26940.0,24476.0
"Fruits, Autres",305.0,1173410.0,105870,175200.0,161610.0,695.0,1301085.0,1173411.0
Graines Colza/Moutarde,49215.0,1460.0,54405,123595.0,108755.0,2025.0,401675.0,1461.0
Graines de tournesol,23470.0,1920.0,53950,23555.0,27235.0,17925.0,213790.0,1921.0
Graisses Animales Crue,7945.0,64960.0,82315,27740.0,27910.0,62115.0,136000.0,64961.0
Haricots,4125.0,77065.0,75990,17435.0,15875.0,295.0,91415.0,77066.0
Huile d'Olive,5.0,12980.0,56230,9745.0,7830.0,1475.0,14450.0,12981.0
Huile de Colza&Moutarde,3500.0,57510.0,52160,42210.0,38750.0,89705.0,150730.0,57511.0
Huile de Soja,55.0,135665.0,84065,57120.0,54765.0,133395.0,269845.0,135666.0
Huiles de Foie de Poisso,20.0,60.0,9070,125.0,30.0,10.0,90.0,61.0
Huiles de Poissons,2085.0,335.0,29645,4160.0,4015.0,2240.0,4670.0,336.0
Ignames,40.0,975.0,8715,415.0,160.0,0.0,1060.0,976.0
Lait - Excl Beurre,418025.0,3383735.0,110880,632930.0,626655.0,94050.0,3994905.0,3383736.0
"Légumes, Autres",424565.0,5937870.0,105570,223905.0,263640.0,2540.0,6901100.0,5937871.0
Légumineuses Autres,35705.0,130110.0,70540,27885.0,26580.0,2480.0,187405.0,130111.0
Manioc,453405.0,374545.0,55460,344180.0,134250.0,177770.0,1115555.0,374546.0
Maïs,3498975.0,673690.0,102895,650490.0,645195.0,1122945.0,5864345.0,673691.0
Millet,8030.0,9765.0,36680,1735.0,710.0,5.0,20295.0,9766.0
"Mollusques, Autres",190.0,149810.0,50220,14890.0,19585.0,190.0,150380.0,149811.0
Oeufs,365.0,281525.0,76645,13380.0,13390.0,4325.0,320100.0,281526.0
Oignons,2360.0,320775.0,82490,34570.0,34075.0,65.0,350915.0,320776.0
"Oranges, Mandarines",55.0,537420.0,100150,178395.0,191380.0,610.0,576280.0,537421.0
Orge,459945.0,34370.0,102525,206085.0,211000.0,3305.0,715070.0,34371.0
Patates douces,334890.0,351380.0,25320,1705.0,2080.0,155.0,723550.0,351381.0
Perciform,5630.0,122255.0,68875,64960.0,54565.0,530.0,130010.0,122256.0
Plantes Aquatiques,1560.0,71535.0,22685,1145.0,1890.0,40295.0,113395.0,71536.0
"Plantes Oleiferes, Autre",9815.0,3195.0,65230,18390.0,32400.0,10995.0,57750.0,3196.0
Pois,24825.0,31755.0,67690,26555.0,23145.0,140.0,63810.0,31756.0
Poissons Eau Douce,2300.0,334975.0,65575,34260.0,40165.0,20015.0,357900.0,334976.0
"Poissons Marins, Autres",7100.0,52660.0,74240,21440.0,29755.0,785.0,60575.0,52661.0