In [35]:
import pandas as pd


animauxCsv = pd.read_csv("/Users/yassine/Desktop/data-python/fr_animaux.csv", sep=',')

DateAnmiaux = animauxCsv.loc[animauxCsv['Année'] == 2013]

synthesis = DateAnmiaux.drop(['Symbole','Domaine','Code zone','Code Domaine','Code Élément','Code année','Description du Symbole'], axis=1)
synthesis.rename(columns={'Valeur':'proteine'}, inplace=True)


indexNames = synthesis[synthesis['Élément'] == 'Disponibilité de protéines en quantité (g/personne/jour)']


res = indexNames.groupby(['Zone']).agg({'proteine': sum});



res

                       proteine
Zone
Afghanistan               12.21
Afrique du Sud            36.39
Albanie                   59.41
Algérie                   24.98
Allemagne                 61.49
...                         ...
Émirats arabes unis       41.70
Équateur                  36.50
États-Unis d'Amérique     69.77
Éthiopie                   7.69
Îles Salomon              17.45

[175 rows x 1 columns]